#!/bin/bash

set -e

dir=tests/behaviour

if [[ ! -d $dir/8/solidity/ ]]; then
  # Get solidity semantic tests
  git clone --no-checkout -b v0.8.14 --depth=1 https://github.com/ethereum/solidity.git $dir/8/solidity

  pushd $dir/8/solidity
  git config core.sparseCheckout true
  echo "test/libsolidity/semanticTests" > .git/info/sparse-checkout
  git checkout v0.8.14
  popd
fi


if [[ ! -d $dir/7/solidity/ ]]; then
  # Get solidity semantic tests
  git clone --no-checkout -b v0.7.6 --depth=1 https://github.com/ethereum/solidity.git $dir/7/solidity

  pushd $dir/7/solidity
  git config core.sparseCheckout true
  echo "test/libsolidity/semanticTests" > .git/info/sparse-checkout
  git checkout v0.7.6

  # Add pragma for version 7 because warp chooses the latest version if none is
  # specified
  for solFile in $(find . -name "*.sol" -type f);
  do
      printf '%s\n%s\n' "pragma solidity ^0.7.6;" "$(cat "$solFile")" > "$solFile"
  done;

  popd
fi


######### TODO get a version of isoltest for each platform and generate
######### test_calldata.ts instead of having it checked in
# # Generate calldata
case "$(uname -s)" in
  Darwin*)
    isoltest=$dir/bin/darwin
    ;;
  Linux*)
    isoltest=$dir/bin/linux
    ;;
esac

# # Typescript was not resolving the type of the calldata json
# # generated by isoltest nore was it enjoying the empty stub
# # that was used as a placeholder. This way ts properly understands
# # the type of the data.
cat > $dir/test_calldata.ts <<- EOM
import { ITestCalldata } from './expectations/semantic';

const testsV7 : {[file: string]: ITestCalldata[] | null} =
EOM
$isoltest/7/isoltest --print-test-expectations \
  --testpath $dir/7/solidity/test/libsolidity/semanticTests/ \
  >> $dir/test_calldata.ts
cat > $dir/test_calldata.ts <<- EOM
const testsV8 : {[file: string]: ITestCalldata[] | null} =
EOM
$isoltest/8/isoltest --print-test-expectations \
  --testpath $dir/8/solidity/test/libsolidity/semanticTests/ \
  >> $dir/test_calldata.ts
cat >> $dir/test_calldata.ts <<- EOM
const tests = {...testsV7, ...testsV8 };
export default tests;
EOM
